function tbl = loaddropfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CBIAAMERGE = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  CBIAAMERGE = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  CBIAAMerge = importfile("S:\csl447\nga_proj\data\fg5\CBI_AA Merge.drop.txt", [5, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Jul-2021 18:51:27

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [5, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 31);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Set", "Drp", "Time", "DOY", "Year", "Gravity", "Sigma", "Error", "Tide", "Load", "Baro", "Polar", "Transfer", "Refxo", "Tilt", "Diffraction", "SelfAttract", "SysResp", "Temp", "Ion", "Spring", "Laser", "Pres", "Chan5", "Chan6", "Chan7Seismic", "Chan8", "Chan9", "Chan10", "LaserLock", "Accept"];
opts.VariableTypes = ["double", "double", "string", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["SysResp", "LaserLock"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

% Convert the times to MATLAB datetime format and add to table as column
t_str = tbl.Year + ' ' + tbl.DOY + ' ' + tbl.Time;
t = datetime(t_str,'InputFormat','uuu DDD HH:mm:ss');

tbl = addvars(tbl,t,'before','Set');


end